### ISSUE TITLE
Timeout of Tbar

### ISSUE THREAD

**Issue by DehengYang** [SerVal-DTF/TBar#2]
Dear Sir,
Sorry for disturbing you with this issue.

When I am reading the Tbar code, it seems that TBar does not have a time limit for the whole repair process. The only timeout that can be seen in Tbar seems to be the shell_time_out.

So my question is that how Tbar controls the time budget (i.e., 3 hours mentioned in the paper)?

Thanks!
Dale

**Comment by BruceKuiLiu** [comment]
Hello @DehengYang , we execute TBar on our HPC machine. The time limitation (i.e., 3 hours) was set when we apply HPC resource for executing TBar. After the execution time of TBar on HPC reaches at 3 hours, HPC will kill the TBar jobs directly.

**Comment by DehengYang** [comment]
Thank you for your detailed answer!
