### ISSUE TITLE
Potential Bug in ConditionalExpressionMutator ?

### ISSUE THREAD

**Issue by WuYff** [SerVal-DTF/TBar#6]
Hello, I find that [ExpressionReplacer](https://github.com/SerVal-DTF/TBar/blob/master/src/main/java/edu/lu/uni/serval/tbar/fixpatterns/ConditionalExpressionMutator.java#L227) defined in ConditionalExpressionMutator class  is not used anywhere. 
And I noticed [this block of code](https://github.com/SerVal-DTF/TBar/blob/master/src/main/java/edu/lu/uni/serval/tbar/fixpatterns/ConditionalExpressionMutator.java#L40):
<img width="1003" alt="tbar_bug" src="https://user-images.githubusercontent.com/39701893/114211314-11095a80-9993-11eb-8aee-08d2b8a6af66.png"> 
It seems that line 50 should be ExpressionReplacer, not ExpressionRemover again.
Is this a bug?

**Comment by Kui-Liu** [comment]
No, it is for the bug in conditional expression (i.e., condExp ? a : b).
